spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: http://localhost:8000
              predicates:
                - Path=/order/**
              filters:
                - RewritePath=/order/(?<segment>.*), /${segment}
server:
  port: 9090

