spring:
  application:
    name: order-service

server:
  port: 8000
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: changeit
    #trust-store: classpath:truststore.jks
    #trust-store-password: changeit
    #client-auth: need

inventory:
  service: https://localhost:8001/inventory
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: trace
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
