spring:
  application:
    name: order-service

server:
  port: 8000

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: trace
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
